### ISSUE TITLE
NoSuchMethodError on runtime

### ISSUE THREAD

**Issue by Bethibande** [Bethibande/kotatsu-java-stub#3]
### Bug
- There is a runtime error caused by the kotatsu parsers library.
- I would assume this error might be caused by different coroutines/kotlin versions used by this library and the kotatsu-parsers library.
```
Caused by: java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism$default(kotlinx.coroutines.CoroutineDispatcher, int, java.lang.String, int, java.lang.Object)'
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser$loadChapters$tail$1.invokeSuspend(MangaDexParser.kt:355) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser$loadChapters$tail$1.invoke(MangaDexParser.kt) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser$loadChapters$tail$1.invoke(MangaDexParser.kt) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser.loadChapters(MangaDexParser.kt:352) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser.access$loadChapters(MangaDexParser.kt:30) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at org.koitharu.kotatsu.parsers.site.all.MangaDexParser$loadChapters$1.invokeSuspend(MangaDexParser.kt) ~[kotatsu-parsers-f3d14e101c.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith$$$capture(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.25.jar:1.9.25-release-852]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt) ~[kotlin-stdlib-1.9.25.jar:1.9.25-release-852]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:na]
```

**Comment by Bethibande** [comment]
The error seems to have been an incorrect coroutines version, due to some external libraries in the project where the error occurred.
Including the correct coroutines version in the dependencies of your project fixes this error.
```kotlin
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.9.0")
```
